/**
 * Created by ycb on 2017/7/17.
 */
export const OUT_LOGIN = 'OUT_LOGIN';
export const RECORD_USER_INFO = 'RECORD_USER_INFO';
export const INIT_USER_INFO = 'INIT_USER_INFO';
export const CHANGE_TOP_SHOW_HIDE = 'CHANGE_TOP_SHOW_HIDE';
export const LOG_IN_AUTHORITY = 'LOG_IN_AUTHORITY';
export const TASK_CATEGORY_LIST = 'TASK_CATEGORY_LIST';
export const GET_SEVER_TIME = 'GET_SEVER_TIME';
export const TASK_MANAGEMENT_COUNT_INFO = 'TASK_MANAGEMENT_COUNT_INFO';
export const SHOW_MERCHANT_GUIDE = 'SHOW_MERCHANT_GUIDE';
export const ONLY_SHOWKER_SHOW = 'ONLY_SHOWKER_SHOW';
export const SET_WECHART_SHOW = 'SET_WECHART_SHOW';
export const SET_WECHART_RES = 'SET_WECHART_RES';
