/**
 * Created by ycb on 2017/7/17.
 */
export const OUT_LOGIN = 'OUT_LOGIN';
export const RECORD_USER_INFO = 'RECORD_USER_INFO';
export const INIT_USER_INFO = 'INIT_USER_INFO';
export const CHANGE_TOP_SHOW_HIDE = 'CHANGE_TOP_SHOW_HIDE';
export const CHANGE_BOTTOM_SHOW_HIDE = 'CHANGE_BOTTOM_SHOW_HIDE';
export const LOG_IN_AUTHORITY = 'LOG_IN_AUTHORITY';
export const ROLE_AUTHORITY = 'ROLE_AUTHORITY';
export const TASK_CATEGORY_LIST = 'TASK_CATEGORY_LIST';
export const GET_SEVER_TIME = 'GET_SEVER_TIME';
export const TASK_MANAGEMENT_COUNT_INFO = 'TASK_MANAGEMENT_COUNT_INFO';
export const SET_WECHART_SHOW = 'SET_WECHART_SHOW';
export const SET_WECHART_RES = 'SET_WECHART_RES';
export const SET_DISCOUNT_TASK_CATEGORY = 'SET_DISCOUNT_TASK_CATEGORY';
export const SET_SHOW_TOP_CATEGORY_RES = 'SET_SHOW_TOP_CATEGORY_RES';
export const SET_ACTIVITY_CATEGORY = 'SET_ACTIVITY_CATEGORY';
export const SYSTEM_CONFIG_INFORMATION = 'SYSTEM_CONFIG_INFORMATION';
